version: "3.8"

services:
  nginx:
    image: base_nginx
    container_name: base_nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    depends_on:
      - "backend"
      - "client"
    ports:
      - $HOST_PORT:80
    environment:
      TZ: "Asia/Tokyo"
    tty: true
    links:
      - client:base_client
      - backend:base_web_api

  backend:
    image: base_web_api
    container_name: base_web_api
    build:
      context: .
      dockerfile: ./webapi/Dockerfile
    tty: true
    volumes:
      - ./webapi/.:/app

  client:
    image: base_client
    container_name: base_client
    build:
      context: .
      dockerfile: ./client/Dockerfile
      args:
        HOST_ADDRESS: $HOST_ADDRESS
        PORT: $HOST_PORT
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client/public/.:/app/public/
      - ./client/src/.:/app/src/

networks:
  base_app_network:
    driver: bridge
    ipam:
      driver: default
